<?xml version="1.0"?>
<!DOCTYPE dia:diagram [
<!ELEMENT dia:diagram (dia:diagramdata , dia:layer*)>
<!ATTLIST dia:diagram xmlns:dia CDATA #FIXED "http://www.lysator.liu.se/~alla/dia/">
<!ELEMENT dia:diagramdata (dia:attribute)*>
<!ELEMENT dia:layer (dia:object | dia:group)*>
<!ATTLIST dia:layer dia:name CDATA #REQUIRED>
<!ATTLIST dia:layer dia:visible (true | false) #REQUIRED>
<!ELEMENT dia:object (dia:attribute* , dia:connections?)>
<!ATTLIST dia:object dia:type CDATA #REQUIRED>
<!ATTLIST dia:object dia:version NMTOKEN #REQUIRED>
<!ATTLIST dia:object dia:id ID #REQUIRED>
<!ELEMENT dia:connections (dia:connection)*>
<!ELEMENT dia:connection EMPTY>
<!ATTLIST dia:connection dia:handle NMTOKEN #REQUIRED>
<!ATTLIST dia:connection dia:to IDREF #REQUIRED>
<!ATTLIST dia:connection dia:connection NMTOKEN #REQUIRED>
<!ELEMENT dia:group (dia:object | dia:group)*>
<!ELEMENT dia:attribute (dia:composite | dia:int | dia:enum | dia:real | dia:boolean | dia:color | dia:point | dia:rectangle | dia:string | dia:font)*>
<!ATTLIST dia:attribute dia:name CDATA #REQUIRED>
<!ELEMENT dia:composite (dia:attribute)*>
<!ATTLIST dia:composite dia:type CDATA #IMPLIED>
<!ELEMENT dia:int EMPTY>
<!ATTLIST dia:int dia:val NMTOKEN #REQUIRED>
<!ELEMENT dia:enum EMPTY>
<!ATTLIST dia:enum dia:val NMTOKEN #REQUIRED>
<!ELEMENT dia:real EMPTY>
<!ATTLIST dia:real dia:val CDATA #REQUIRED>
<!ELEMENT dia:boolean EMPTY>
<!ATTLIST dia:boolean dia:val (true | false) #REQUIRED>
<!ELEMENT dia:color EMPTY>
<!ATTLIST dia:color dia:val CDATA #REQUIRED>
<!ELEMENT dia:point EMPTY>
<!ATTLIST dia:point dia:val CDATA #REQUIRED>
<!ELEMENT dia:rectangle EMPTY>
<!ATTLIST dia:rectangle dia:val CDATA #REQUIRED>
<!ELEMENT dia:string EMPTY>
<!ATTLIST dia:string dia:val CDATA #IMPLIED>
<!ELEMENT dia:font EMPTY>
<!ATTLIST dia:font dia:name CDATA #REQUIRED>
]>
<dia:diagram xmlns:dia="http://www.lysator.liu.se/~alla/dia/">
  <dia:diagramdata>
    <dia:attribute dia:name="background">
      <dia:color dia:val="#ffffff"/>
    </dia:attribute>
  </dia:diagramdata>
  <dia:layer dia:name="Background" dia:visible="true">
    <dia:object dia:type="Standard - Line" dia:version="0" dia:id="O0">
      <dia:attribute dia:name="obj_pos">
        <dia:point dia:val="1.95,6.85"/>
      </dia:attribute>
      <dia:attribute dia:name="obj_bb">
        <dia:rectangle dia:val="1.9,6.8;11,8.55"/>
      </dia:attribute>
      <dia:attribute dia:name="conn_endpoints">
        <dia:point dia:val="1.95,6.85"/>
        <dia:point dia:val="10.95,8.5"/>
      </dia:attribute>
      <dia:attribute dia:name="line_color">
        <dia:color dia:val="#000000"/>
      </dia:attribute>
      <dia:attribute dia:name="line_width">
        <dia:real dia:val="0.1"/>
      </dia:attribute>
      <dia:attribute dia:name="line_style">
        <dia:enum dia:val="0"/>
      </dia:attribute>
      <dia:attribute dia:name="start_arrow">
        <dia:enum dia:val="0"/>
      </dia:attribute>
      <dia:attribute dia:name="end_arrow">
        <dia:enum dia:val="0"/>
      </dia:attribute>
      <dia:connections>
        <dia:connection dia:handle="1" dia:to="O2" dia:connection="3"/>
      </dia:connections>
    </dia:object>
    <dia:object dia:type="Standard - Text" dia:version="0" dia:id="O1">
      <dia:attribute dia:name="obj_pos">
        <dia:point dia:val="4.8,4.75"/>
      </dia:attribute>
      <dia:attribute dia:name="obj_bb">
        <dia:rectangle dia:val="2.579,3.96359;7.021,4.96359"/>
      </dia:attribute>
      <dia:attribute dia:name="text">
        <dia:composite dia:type="text">
          <dia:attribute dia:name="string">
            <dia:string dia:val="sdfsdfg"/>
          </dia:attribute>
          <dia:attribute dia:name="font">
            <dia:font dia:name="Courier"/>
          </dia:attribute>
          <dia:attribute dia:name="height">
            <dia:real dia:val="1"/>
          </dia:attribute>
          <dia:attribute dia:name="pos">
            <dia:point dia:val="4.8,4.75"/>
          </dia:attribute>
          <dia:attribute dia:name="color">
            <dia:color dia:val="#000000"/>
          </dia:attribute>
          <dia:attribute dia:name="alignment">
            <dia:enum dia:val="1"/>
          </dia:attribute>
        </dia:composite>
      </dia:attribute>
    </dia:object>
    <dia:object dia:type="Standard - Box" dia:version="0" dia:id="O2">
      <dia:attribute dia:name="obj_pos">
        <dia:point dia:val="10.95,7.5"/>
      </dia:attribute>
      <dia:attribute dia:name="obj_bb">
        <dia:rectangle dia:val="10.9,7.45;13.05,9.55"/>
      </dia:attribute>
      <dia:attribute dia:name="elem_corner">
        <dia:point dia:val="10.95,7.5"/>
      </dia:attribute>
      <dia:attribute dia:name="elem_width">
        <dia:real dia:val="2.05"/>
      </dia:attribute>
      <dia:attribute dia:name="elem_height">
        <dia:real dia:val="2"/>
      </dia:attribute>
      <dia:attribute dia:name="border_width">
        <dia:real dia:val="0.1"/>
      </dia:attribute>
      <dia:attribute dia:name="border_color">
        <dia:color dia:val="#000000"/>
      </dia:attribute>
      <dia:attribute dia:name="inner_color">
        <dia:color dia:val="#ffffff"/>
      </dia:attribute>
      <dia:attribute dia:name="line_style">
        <dia:enum dia:val="0"/>
      </dia:attribute>
    </dia:object>
  </dia:layer>
</dia:diagram>
